name: "Update datasets"
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Download and merge
        run: |
          python download_rivm_corona.py
          python merge_data.py
      - uses: r-lib/actions/setup-r@master
        continue-on-error: true
      - name: Install R dependencies
        run: |
          options(install.packages.check.source = "no")
          install.packages(c("tidyverse"), type="binary")
        shell: Rscript {0}
        continue-on-error: true
      - name: Render plots
        run: Rscript plots.R
        continue-on-error: true
      - name: Commit files
        run: |
          git config --local user.email "jonathandebruinos@gmail.com"
          git config --local user.name "J535D165 Action"
          git add .
          git commit -m "Add new datasets"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
