name: "Download datasets"
on:
  schedule:
    - cron:  '20,50 12-15 * * *'

jobs:
  download-rivm-geo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Download and merge
        run: |
          python workflows/rivm/data_rivm_download.py
          python workflows/rivm/merge_data.py
          python workflows/rivm/data_rivm_geo.py
          python workflows/json/json-api.py
      - name: Commit files
        run: |
          git config --local user.email "jonathandebruinos@gmail.com"
          git config --local user.name "J535D165 Action"
          git add .
          git commit -m "Update geo data"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true
  download-lcps:
    name: Download LCPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Download and merge
        run: |
          python workflows/lcps/lcps.py
          python workflows/lcps/data-ic_lcps.py
      - name: Commit files
        run: |
          git config --local user.email "jonathandebruinos@gmail.com"
          git config --local user.name "J535D165 Action"
          git add .
          git commit -m "Update LCPS data"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true
  download-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Download and merge
        run: |
          python workflows/rivm/data_rivm_dashboard.py
      - name: Commit files
        run: |
          git config --local user.email "jonathandebruinos@gmail.com"
          git config --local user.name "J535D165 Action"
          git add .
          git commit -m "Update Dashboard data"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true
  download-gov-measures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Download and merge
        run: |
          python workflows/measures/measures.py
      - name: Commit files
        run: |
          git config --local user.email "jonathandebruinos@gmail.com"
          git config --local user.name "J535D165 Action"
          git add .
          git commit -m "Update measures data"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true

